<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'user_id' => NULL,
                'title' => 'Sorts persistants: Beasts of Chaos',
                'metaTitle' => 'Beasts of Chaos',
                'slug' => 'Battlemagic-Beasts-Of-Chaos-2018',
                'summary' => 'Ce kit plastique contient les composants nécessaires pour assembler 3 Sorts Persistants utilisables par les sorciers Beasts of Chaos dans les parties de Warhammer Age of Sigmar.' ,
                'price'	=> 30,
                'discount' =>	0,
                'quantity' =>	9,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Le nécro-séisme cataclysmique de Shyish a submergé les Royaumes Mortels sous la puissance de l'éther. Les incantations manifestent un pouvoir sans précédent animé d'une conscience effroyable, et que chacun prenne garde – les sorts persistants ainsi suscités peuvent se retourner contre leur lanceur aussi promptement qu'ils peuvent dévaster les rangs adverses. Que ce soit en déchaînant des gueules avides désincarnées pour dévorer vos ennemis, ou en dressant des barricades prismatiques pour protéger vos flancs, le combat au temps de l'Arcanum Optimar n'a rien de commun avec ce que vous avez connu." ,
                'sellQuantity' => 0,
                'category_id' => 5,
            ],
            [
                'user_id' => NULL,
                'title' => 'Kavalos Deathriders',
                'metaTitle' => 'Kavalos Deathriders',
                'slug' => 'Ossiarch-Bonereapers-Kavalos-Deathriders-2019',
                'summary' => "Ce kit plastique permet d'assembler 5 Kavalos Deathriders, et il est fourni avec 5 socles ovales Citadel de 60mm." ,
                'price'	=> 45,
                'discount' =>	0,	
                'quantity' =>	10,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Cavalerie lourde des légions Ossiarch Bonereapers, les Kavalos Deathriders chevauchent de macabres destriers caparaçonnés. Ils galopent en formation de fer de lance, brisant les lignes adverses à chacune de leurs charges féroces.

                Les Kavalos Deathriders peuvent être armés au choix de lames de nadirite ou de lances de nadirite, des armes qui aspirent la force vitale de l'ennemi. Le kit propose aussi l'option d'inclure un Mortrek Hekatos et un Necrophoros porte-étendard pour prendre la tête de la charge dévastatrice.",
                'sellQuantity' => 0,
                'category_id' => 6,
            ],
            [
                'user_id' => NULL,
                'title' => 'Lord-Celestant on Stardrake',
                'metaTitle' => 'Lord-Celestant on Stardrake',
                'slug' => 'Stormcast-Eternals-Stardrake',
                'summary' => "Ce kit plastique comprend tout le nécessaire pour assembler un Lord-Celestant sur Stardrake, ou un Drakesworn Templar, la vengeance céleste incarnée, armé d'une hache tempête, d'un marteau galvanique, ou d'une lance d'orage et d'un arc Skybolt." ,
                'price'	=> 125,
                'discount' =>	0,	
                'quantity' =>	5,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Même parmi les rangs glorieux des Stormcast Eternals et la hiérarchie stellaire des Enfants de Dracothion, seuls les plus valeureux et les plus nobles peuvent commander une Chambre Extremis. Le Lord-Celestant et le Stardrake sont investis d'une énergie céleste telle qu'ils émettent une aura d'azur. Ils disposent de la puissance des étoiles elles-mêmes…",
                'sellQuantity' => 0,
                'category_id' => 4,
            ],
            [
                'user_id' => NULL,
                'title' => 'Sylvaneth Treelord Ancient',
                'metaTitle' => 'Sylvaneth Treelord Ancient',
                'slug' => 'Sylvaneth-Treelord-Ancient',
                'summary' => "Ce kit plastique contient tout le nécessaire pour monter un Treelord Ancient, l'un des jeteurs de sorts respectés des sylvaneth. Huit farfadets éthérés sont inclus pour le personnaliser, en plus d'un socle ovale Citadel de 105mm. On peut, selon sa préférence l'assembler en tant que Treelord ou Durthu*. Chacune de ces variantes a sa propre tête et option d'arme." ,
                'price'	=> 54,
                'discount' =>	0,	
                'quantity' =>	15,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Esprits sylvestres colossaux dont les pas décidés font trembler la terre, les Treelord Ancients sont parmi les plus anciennes créatures vivantes des Royaumes. En plus d'être des combattants de renom, qui peuvent affronter à branches nues les ennemis les plus résistants, ce sont des mages puissants capables de déchaîner la colère vengeresse des Wyldwoods",
                'sellQuantity' => 0,
                'category_id' => 4,
            ],
            [
                'user_id' => NULL,
                'title' => 'Morathi',
                'metaTitle' => 'Morathi',
                'slug' => 'Daughters-Of-Khaine-Morathi-2018',
                'summary' => "Ce kit plastique contient les composants nécessaires pour assembler Morathi. Elle se décline en deux figurines différentes incluses dans le kit: sa forme aelfique dite High Oracle of Khaine, et sa véritable forme monstrueuse qu'est la Shadow Queen." ,
                'price'	=> 110,
                'discount' =>	0,	
                'quantity' =>	42,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Morathi est une créature de magie, de manipulation et de secret, la Grande Oracle de Khaine, la Reine de l’Ombre et la grande matriarche des Filles de Khaine. Très ancienne, c'est une prophétesse dont la maîtrise de la magie noire est sans égale. Outre sa capacité à invoquer les horreurs du royaume des ténèbres, elle a utilisé sa sorcellerie afin d’adopter une forme avenante – celle d’une aelf radieuse encadrée par une paire d’ailes forgées en métal d’ombre. Sa beauté est si surnaturelle que ses adversaires restent abasourdis de ravissement. Il s’agit là d’une erreur fatale, car Morathi manie sa lance Écorche-coeur avec une efficacité cruelle, et ses ailes acérées sont capables de trancher n’importe quel membre.",
                'sellQuantity' => 0,
                'category_id' => 4,
            ],
            [
                'user_id' => NULL,
                'title' => 'Rotigus',
                'metaTitle' => 'Rotigus',
                'slug' => 'Rotigus-Rainmaker',
                'summary' => "Ce kit plastique contient les composants nécessaires pour assembler Rotigus, un Great Unclean One. Son aspect a beaucoup de points communs avec le Great Unclean One standard, une montagne de graisse répugnante – son abdomen béant est garni de dents acérées ou cassées, et couvert de furoncles et de lésions." ,
                'price'	=> 110,
                'discount' =>	0,	
                'quantity' =>	18,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Un des démons majeurs de Nurgle est un voyageur infatigable. Il parcourt les terres des mortels et des dieux, et partout où il se rend, une vie répugnante prolifère. C’est Rotigus le Généreux, et il aime son travail. En sa présence, la flore et la faune grouillent et enflent, et ses dons sont tels qu'il ne juge pas utile de porter une arme, mais juste son broussin, qui pourrit et se régénère constamment à partir d'une pousse pour engendrer des maladies toujours plus infectieuses. Il manifeste le Déluge de Nurgle – un orage nauséabond qui flotte en permanence au-dessus de son corps colossal, et dont la pluie immonde répand la bénédiction de Nurgle dans tous les recoins du champ de bataille. ",
                'sellQuantity' => 0,
                'category_id' => 5,
            ],
            [
                'user_id' => NULL,
                'title' => 'Belakor, the Dark Master',
                'metaTitle' => 'Belakor, the Dark Master',
                'slug' => 'Chaos-Daemons-Belakor-The-Dark-Master-2021',
                'summary' => "Ce kit plastique en 85 composants permet d'assembler un Be'lakor, the Dark Master, fourni avec 1x socle rond Citadel de 100mm. Ce kit contient de multiples options pour monter Be'lakor dans le thème d'une armée de Slaves to Darkness pour Warhammer Age of Sigmar, d'une armée de Démons du Chaos pour Warhammer 40,000 ou bien dans un thème neutre pour convenir aux deux jeux." ,
                'price'	=> 110,
                'discount' =>	0,	
                'quantity' =>	0,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Be'lakor, le Maître des Ténèbres, est le premier des Princes Démons et un champion accompli du Chaos. Ceint d'ombres éthérées et survolant le champ de bataille porté par ses ailes monstrueuses, Be'lakor observe avec dédain les efforts voués à l'échec de ses ennemis contre ses desseins diaboliques. Alors que les Royaumes Mortels sombrent dans le chaos consécutif à la cataclysmique Guerre des Âmes, le Premier Prince sait que son heure est venue. Ni les hommes ni les dieux ne sauraient entraver sa grande ambition.",
                'sellQuantity' => 0,
                'category_id' => 5,
            ],
            [
                'user_id' => NULL,
                'title' => 'Lord of Change',
                'metaTitle' => 'Lord of Change',
                'slug' => 'lord-of-change-2016',
                'summary' => "Ce kit plastique contient les composants nécessaires pour assembler un Lord of Change. Ce sujet imposant est une pièce centrale de choix pour toute armée de Tzeentch, et il arbore la symbolique de son dieu pour souligner son statut de maître des arcanes. Ses ailes immenses peuvent se monter dans 2 positions différentes, et il a le choix entre 3 têtes sinistres. Il est armé d'un bâton de Tzeentch, qui peut s'achever par un symbole de son dieu ou par une lame ardente, ou bien d'une baguette de sorcellerie et d'une épée maléfique. Il est accompagné de 2 Brimstone Horrors pouvant orner son socle." ,
                'price'	=> 110,
                'discount' =>	0,	
                'quantity' =>	14,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Démons majeurs de Tzeentch entre tous, les Lords of Change irradient la magie brute. Rien qu'en pointant une serre, un Lord of Change peut plonger ses ennemis dans un cauchemar, ou les vaporiser avec les maleflammes de Tzeentch. Un tel être peut dérober les sorts adverses à son profit, ou projeter des rayons mutagènes avec son sceptre de sorcier pour détruire des formations ennemies entières.",
                'sellQuantity' => 0,
                'category_id' => 5,
            ],
            [
                'user_id' => NULL,
                'title' => 'Bloab Rotspawned',
                'metaTitle' => 'Bloab Rotspawned',
                'slug' => 'Rotbringers-Bloab-Rotspawned',
                'summary' => "Ce kit plastique de soixante-treize pièces permet d'assembler un Bloab Rotspawned chevauchant son pox maggoth, Bilespurter. Muni d'une armure du Chaos corrodée et d'une arme lourde, Bloab est un canal vivant pour Grand-père Nurgle, ce que sa figurine démontre en tout point. Son visage est bouffi et boudiné, et des mouches et asticots démoniaques le drapent comme un manteau. Contient un socle rond Citadel de 100mm." ,
                'price'	=> 60,
                'discount' =>	0,	
                'quantity' =>	11,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Vu de loin, le sorcier du Chaos Bloab Rotspawned semble constamment entouré de nuées d'insectes surnaturels. Seuls ses compagnons d'armes de la tribu de la Corne de Glace savent qu'en fait, Bloab et la nuée ne font qu'un.",
                'sellQuantity' => 0,
                'category_id' => 6,
            ],
            [
                'user_id' => NULL,
                'title' => 'Harbinger of Decay',
                'metaTitle' => 'Harbinger of Decay',
                'slug' => 'Harbinger-Of-Decay',
                'summary' => "Ce kit résine finement détaillé se compose de 8 pièces et d'un socle ovale Citadel de  75x41.5mm, permettant d'assembler un Harbinger of Decay. " ,
                'price'	=> 31,
                'discount' =>	0,	
                'quantity' =>	18,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Bouffi et chevauchant un destrier monstrueux, le Harbinger Of Decay est invraisemblablement puissant. Sûr de l'approbation de son dieu tutélaire, il se bat en commettant fièrement des méfaits dégoûtants, qui lui valent une pluie de récompenses ignobles. Comme de juste, il est censé les partager, et quand l'ennemi s'approche, il profite des sensations que l'épée de pourriture dispense.",
                'sellQuantity' => 0,
                'category_id' => 6,
            ],
            [
                'user_id' => NULL,
                'title' => 'Corpse Cart avec Brasero Infernal',
                'metaTitle' => 'Corpse Cart avec Brasero Infernal',
                'slug' => 'Corpse-Cart-with-Balefire-Brazier-2018',
                'summary' => "Cette boîte contient 1 kit plastique de Corpse Cart. " ,
                'price'	=> 23,
                'discount' =>	0,	
                'quantity' =>	1,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Entre les foules de Zombies titubants et les meutes de Dire Wolves grincent les hideuses Corpse Carts. Conduites par des silhouettes macabres cachées sous un suaire, ces charrettes de bois pourri, de métal rouillé et de chair décomposée sont chargées de fragments de cadavres frémissants. ",
                'sellQuantity' => 0,
                'category_id' => 6,
            ],
            [
                'user_id' => NULL,
                'title' => 'Wight King with Baleful Tomb Blade',
                'metaTitle' => 'Wight King with Baleful Tomb Blade',
                'slug' => 'Deathrattle-Wight-King-2018',
                'summary' => "Ce kit plastique contient un Wight King avec Lame Sépulcrale de l'Enfer, une figurine finement détaillée en 5 composants, fournie avec un socle rond Citadel de 32mm." ,
                'price'	=> 12,
                'discount' =>	0,	
                'quantity' =>	0,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Dans les temps anciens, de puissants seigneurs de guerre se battaient en leurs domaines. À leur mort, ces guerriers brutaux étaient ensevelis profondément, leurs sépultures protégées des pillards et des charognards par une magie païenne. Nombre de ces tombes ont été détruites au fil des siècles, mais il en reste encore beaucoup. Certaines ont été creusées dans des lieux imprégnés de magie noire, où les morts ne connaissent pas le repos, leurs âmes oscillant entre le monde des mortels et celui de l'au-delà. Quand la magie noire s'intensifie, ces anciens seigneurs se dressent hors de leurs cryptes sous forme de Wight Kings aux yeux luisant d'une vie surnaturelle. La plus légère caresse de leur lame peut drainer la vie de leurs ennemis, ou trancher à travers chair et os sans la moindre difficulté.
                ",
                'sellQuantity' => 0,
                'category_id' => 6,
            ],
            [
                'user_id' => NULL,
                'title' => 'Easy to Build: Reikenor the Grimhailer',
                'metaTitle' => 'Reikenor the Grimhailer',
                'slug' => 'Etb-Nighthaunt-Reikenor-The-Grimhailer-2018',
                'summary' => "Ce kit est fourni en 11 composants, plus un socle ovale scénique Citadel de 75mm. Conçu pour être le plus facile possible à assembler pour les nouveaux hobbyistes tout en étant suffisamment détaillé pour plaire aux vétérans les plus exigeants, ce kit permet de monter Reikenor the Grimhailer sur sa monture, le Nightmare Kyallaron. " ,
                'price'	=> 32,
                'discount' =>	0,	
                'quantity' =>	14,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Roi-sorcier versé dans la magie d’améthyste de son vivant, Reikenor s’est opposé à Nagash. À présent mort-vivant, il est le Sombre Chantre, condamné à servir le Grand Nécromancien en tant que chef de ses faucheurs d’âmes. Peu de spectacles sont aussi sinistres que le spectre-sorcier chevauchant sa monture ailée à la lueur de ses bougies de cadavres. Grâce à ses incantations, Reikenor peut invoquer une tempête spectrale – un cyclone de magie d’améthyste qui attise les âmes récemment arrachées à leur corps. Son sort les incite à attaquer leurs anciens camarades. Il crée un ouragan spectral dans lequel des fantômes affaiblissent et lacèrent les vivants. Ainsi s’exerce la vengeance de Nagash sur ceux qui le contrarient. ",
                'sellQuantity' => 0,
                'category_id' => 6,
            ],
            [
                'user_id' => NULL,
                'title' => 'Cairn Wraith',
                'metaTitle' => 'Cairn Wraith',
                'slug' => 'Nighthaunt-Cairn-Wraith-2018',
                'summary' => "Ce kit plastique contient un Cairn Wraith, figurine finement détaillée en 7 composants (dont trois têtes au choix), avec un socle rond Citadel de 25mm. " ,
                'price'	=> 10,
                'discount' =>	0,	
                'quantity' =>	2,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Les Cairn Wraiths sont parmi les plus puissants des morts-vivants. Dénués de substance physique, ils peuvent drainer la vie d'un mortel par simple contact. Leur simple présence remplit l'air d'effroi, et la plupart de ceux qui leur font face meurent de peur bien avant de risquer d'être tués. Ces esprits vengeurs et rageurs assaillent leurs ennemis à grands coups de leurs antiques faux ensorcelées. Par contre, quiconque parvient à riposter se rend compte que ses pitoyables attaques passent à travers le Cairn Wraith, en ne touchant qu'un air vicié et des haillons. Les Wraiths ne tardent pas à châtier pareille insolence. ",
                'sellQuantity' => 0,
                'category_id' => 6,
            ],
            [
                'user_id' => NULL,
                'title' => 'Kritza, The Rat Prince',
                'metaTitle' => 'Kritza, The Rat Prince',
                'slug' => 'Kritza-The-Rat-Prince-2021',
                'summary' => "Ce kit plastique en 9 composants permet d'assembler une figurine de Kritza, et il est fourni avec un socle ovale Citadel de 60mm. " ,
                'price'	=> 22,
                'discount' =>	0,	
                'quantity' =>	7,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Si Kritza joue au noble et s’asperge de parfums nauséeux, son âme est en réalité aussi infâme que les égouts d’Ulfenkarn où il a établi son repaire. Le Prince des Rats n'en est pas moins un adversaire rusé, qui revient après chaque défaite pour se venger cruellement. ",
                'sellQuantity' => 0,
                'category_id' => 6,
            ],
            [
                'user_id' => NULL,
                'title' => 'Mortis Engine',
                'metaTitle' => 'Mortis Engine',
                'slug' => 'Machine-Mortis-des-Comtes-Vampires',
                'summary' => "Ce kit de grande taille contient 87 composants en plastique, ainsi qu’un socle ovale de 120x92mm, avec lesquels assembler une Mortis Engine, un Coven Throne ou un Bloodseeker Palanquin. " ,
                'price'	=> 49,
                'discount' =>	0,	
                'quantity' => 45,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Une fois défunts (a priori), les restes des puissants nécromanciens sont confinés au sein d’une Mortis Engine et menés au combat par une horde d’esprits liée à l’engin infernal, tandis que des banshees hululantes ondulent autour, spectacle terrifiant entre tous.

                La Mortis Engine est une figurine imposante dont la moitié inférieure est éthérée au-delà de la raison. Des volutes de brume fantomatiques, agrémentées de ci, de là de pièces d’armure, s’élèvent, menée pat des cavaliers squelettiques sur destriers caparaçonnés. La moitié supérieure de la figurine accueille le sinistre Corpsemaster, entouré de banshees. Ce kit impressionnant comporte une foule de détails comme des lanternes, des squelettes, des coussins décadents et des flammes magiques. ",
                'sellQuantity' => 0,
                'category_id' => 6,
            ],
            [
                'user_id' => NULL,
                'title' => 'Intercessors lourds',
                'metaTitle' => 'Intercessors lourds',
                'slug' => 'Space-Marines-Heavy-Intercessors-2021',
                'summary' => "Ce kit plastique en 120 composants permet d'assembler cinq Intercessors lourds, et il est fourni avec cinq socles ronds Citadel de 40mm. L'escouade entière peut être équipée de fusils bolters lourds, de fusils bolters Hellstorm ou de fusils bolters Executor, et un membre peut recevoir un bolter lourd, un bolter lourd Hellstorm, ou un bolter lourd Executor. La boîte contient aussi une planche de décalcomanies pour Space Marines. " ,
                'price'	=> 48,
                'discount' =>	0,	
                'quantity' => 9,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Revêtus d’une épaisse armure Gravis, les Intercessors Lourds sécurisent le terrain et sont inamovibles en défense. Toujours à l’affût de la moindre contre-attaque adverse, ils tiennent leurs positions en lâchant des salves de bolts lourds qui dissuadent l’ennemi, hormis peut-être le plus insensé ou le plus déterminé.

                Les Intercessors lourds sont le nec plus ultra en guerre défensive. Ne cherchez pas plus loin que ce choix de Troupes prodigieusement solide pour tenir les objectifs, tout en érigeant un mur de feu à longue portée avec ses bolters lourds et fusils bolters lourds.",
                'sellQuantity' => 0,
                'category_id' => 7,
            ],
            [
                'user_id' => NULL,
                'title' => 'Primaris Redemptor Dreadnought',
                'metaTitle' => 'Primaris Redemptor Dreadnought',
                'slug' => 'Space-Marines-Primaris-Redemptor-Dreadnought-2020',
                'summary' => "Ce kit plastique contient tous les composants nécessaires pour assembler un Primaris Redemptor Dreadnought. Deux fois plus haut qu'un Space Marine Primaris – et encore plus grand et large que le Dreadnought standard – cette figurine est aussi terrible sur la table que son l'aspect exceptionnellement agressif le suggère." ,
                'price'	=> 53,
                'discount' =>	0,	
                'quantity' => 15,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Le Dreadnought de type Redemptor est une machine de guerre géante qui percute les rangs adverses en brisant les os et en fendant les crânes. Plus grand, plus large et mieux conçu que les Dreadnought traditionnels, ce goliath de guerre est alimenté par un réacteur hyper-dense et des faisceaux de fibres sophistiqués. Il peut accélérer d'un pas lourd à une cadence de course à faire vibrer le sol, pour foncer au mépris des orage d'acier. La conception miraculeuse des connexions neurales du Redemptor permet à son occupant, malgré son incarcération dans le sarcophage pectoral du Dreadnought, d'exercer son contrôle avec une célérité et une dextérité surprenantes.",
                'sellQuantity' => 0,
                'category_id' => 7,
            ],
            [
                'user_id' => NULL,
                'title' => 'Primaris Chaplain',
                'metaTitle' => 'Primaris Chaplain',
                'slug' => 'Space-Marines-Primaris-Chaplain-2020',
                'summary' => "Ce kit plastique contient les composants nécessaire pour assembler un Primaris Chaplain. Dans son armure énergétique Mk X noire de jais aux jambières caractéristiques, il manie avec ferveur son pistolet bolter Absolvor et son crozius arcanum. Sa bure encapuchonnée lui donne un air lugubre prononcé, ce que confortent les pointes, chaînes, crânes et sceaux de pureté dont il est bardé. Son heaume en forme de crâne et son plastron en forme de cage thoracique évoquent la mort qui guette ses ennemis. Son paquetage dorsal comporte un rosarius dont les 12 pointes représentent les Hauts Seigneurs de Terra." ,
                'price'	=> 28,
                'discount' =>	0,	
                'quantity' => 35,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Chefs spirituels de leur Chapitre, les Chaplains sont les prêtres-guerriers qui inspirent la crainte, administrent les rites, conservent la tradition rituelle et encadrent les antiques cérémonies initiatiques, vengeresses et rédemptrices aussi importantes pour un Chapitre Space Marine que le palmarès honorifique et les talents martiaux. Toutes les Compagnies ont leur Chaplain, qui encadre aussi bien les dévotions que les opérations militaires et qui n'est subordonné qu'à son capitaine.",
                'sellQuantity' => 0,
                'category_id' => 7,
            ],
            [
                'user_id' => NULL,
                'title' => 'Exorcist',
                'metaTitle' => 'Exorcist',
                'slug' => 'Adepta-Sororitas-Exorcist-2020',
                'summary' => "Le kit comprend 99 composants dont l'ensemble des options d'armes et d'équipement de l'Exorcist. Figurine fournie avec une planche de décalcomanies Adepta Sororitas. " ,
                'price'	=> 63,
                'discount' =>	0,	
                'quantity' => 15,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "L’Exorcist est une arme qui montre de façon unique comment l’Adepta Sororitas prouve sa dévotion envers l’Empereur-Dieu, en châtiant Ses ennemis hérétiques. Il s’agit d’un autel ambulant dédié à la magnificence du Maître de l’Humanité, une œuvre d’art éblouissante qui progresse sur le champ de bataille tout en émettant des hymnes sacrés. Ces derniers résonnent par-dessus la clameur des combats et gonflent de fierté les coeurs des soldats de l’Imperium. Lorsque des escadrons entiers de ces véhicules avancent, leurs émissions symphoniques combinées transforment un champ de bataille boueux et ensanglanté en un lieu sacré aussi glorieux que le plus gigantesque des cathedrums. Les guerriers exténués reprennent courage en percevant ces cantiques. Les soldats surclassés en nombre et apeurés tiennent de nouveau leurs positions sans faillir. Et lorsque les premières roquettes de l’Exorcist montent en hurlant dans les airs avant de s’abattre, c’est l’ennemi qui est frappé de terreur, et le cours de la bataille change subitement.",
                'sellQuantity' => 0,
                'category_id' => 8,
            ],
            [
                'user_id' => NULL,
                'title' => 'Stormlord',
                'metaTitle' => 'Stormlord',
                'slug' => 'Astra-Militarum-Stormlord-2019',
                'summary' => "Ce kit plastique contient pas moins de 295 composants. Il permet d'assembler au choix un char super-lourd Baneblade, Hellhammer, Banesword, Stormsword, Shadowsword, Banehammer ou Doomhammer à la place d'un Stormlord. Également incluse, 1 planche de décalcomanies pour véhicule de l'Astra Militarum pour ajouter des marquages et insignes. " ,
                'price'	=> 114,
                'discount' =>	0,	
                'quantity' => 55,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Un char super-lourd est à lui seul une présence dominante dans une ligne de bataille de l'Astra Militarum. Sa progression inexorable s'accompagne du tracé d'un large sillage de destruction. Les rangs adverses se rompent bien avant qu'il atteigne leur position, et les rares malheureux qui tiennent leur formation défensive sont réduits en bouillie sous ses énormes maillons de chenilles. Le Stormlord est essentiellement voué au transport de troupes, avec une soute capable d'accueillir quarante gardes impériaux, et en outre son méga-bolter Vulcan le rend particulièrement puissant contre l'infanterie ennemie.",
                'sellQuantity' => 0,
                'category_id' => 8,
            ],
            [
                'user_id' => NULL,
                'title' => 'Knight Valiant',
                'metaTitle' => 'Knight Valiant',
                'slug' => 'Imperial-Knights-Knight-Valiant-2018',
                'summary' => "Ce kit est fourni en 141 composants, plus un socle ovale Citadel de 170x105mm et une planche de décalcomanies pour Imperial Knights. " ,
                'price'	=> 125,
                'discount' =>	0,	
                'quantity' => 45,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Le Knight Valiant élimine ses ennemis par l’application d’une puissance de feu colossale sans discrimination. Il marche implacablement au combat tandis que les tirs ennemis rebondissent sur son bouclier ionique. Le Valiant déchaîne une telle grêle de projectiles en si peu de temps que l’adversaire n’a aucune chance de riposter ni de survivre. Si on ajoute à cela la puissance de feu des canons Siegebreaker, le harpon Thundercoil, le canon Conflagration et les missiles Shieldbreaker, il n’est pas étonnant de constater que les forces ennemies se débandent généralement à la simple vue d’un Valiant. ",
                'sellQuantity' => 0,
                'category_id' => 8,
            ],
            [
                'user_id' => NULL,
                'title' => 'Chaos Lord',
                'metaTitle' => 'Chaos Lord',
                'slug' => 'Chaos-Space-Marines-Chaos-Lord-2019',
                'summary' => "Ce kit permet de monter un Chaos Lord. Il est fourni en 6 composants plastique, plus un socle rond Citadel de 40mm. " ,
                'price'	=> 30,
                'discount' =>	0,	
                'quantity' => 50,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Un Chaos Lord est un roi-guerrier tyrannique qui ne vit que pour se baigner dans le sang de mondes entiers. Il combat pour mettre à genoux des systèmes stellaires au nom de ses divinités tutélaires. Caractérisés par leur ambition implacable et leur orgueil farouche, la plupart des champions du désordre de ce genre furent jadis de nobles capitaines et maîtres de Chapitre de l'Adeptus Astartes, dont l'âme a été pervertie irrémédiablement par des années de guerre sans rémission. ",
                'sellQuantity' => 0,
                'category_id' => 9,
            ],
            [
                'user_id' => NULL,
                'title' => 'Plague Marine Icon Bearer',
                'metaTitle' => 'Plague Marine Icon Bearer',
                'slug' => 'Death-Guard-Plague-Marine-Icon-Bearer-2020',
                'summary' => "Ce kit plastique contient les composants nécessaires pour assembler un Plague Marine Icon Bearer. Armé d'un bolter, muni d'un couteau de la peste sanglé à son paquetage, il traîne une Icône du Désespoir jusqu'en mêlée, en forme de symbole de Nurgle comme il se doit (lequel est représenté à l'aide d'un crâne et d'un casque). Son armure rouillée craque de toutes part tant elle est corrompue, et des tentacules horribles frétillent dans les brèches de sa jambière droite. Il a 4 grenades krak à portée de main et, en guise de touche finale, il porte à la ceinture une tête pourrissante." ,
                'price'	=> 19,
                'discount' => 0,	
                'quantity' => 50,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Voués à Nurgle, les Plague Marines sont pourris, repoussants, et puent la décomposition. Le liquide putrescent qui suinte de leurs plaies corrode leur armure et consume leur peau, mais malgré leurs horribles défigurations, ce sont de redoutables guerriers. Leur cerveau moisi est insensible à la douleur de leur corruption physique, ce qui leur fait pratiquement ignorer la plupart des blessures.",
                'sellQuantity' => 0,
                'category_id' => 9,
            ],
            [
                'user_id' => NULL,
                'title' => 'Biologus Putrifier',
                'metaTitle' => 'Biologus Putrifier',
                'slug' => 'Death-Guard-Biologus-Putrifier-2020',
                'summary' => "Ce kit est fourni en 10 composants, plus un socle rond Citadel de 40mm. " ,
                'price'	=> 19,
                'discount' =>	0,	
                'quantity' => 50,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "L’oeuvre majeure de la Death Guard consiste à diffuser les bienfaits de Nurgle partout dans l’espace réel. Les Biologus Putrifiers y jouent un rôle crucial, car ce sont eux qui raffinent les lots de bouillon de culture produits par les Foul Blightspawn, et les distillent pour les magnifier. Leur râtelier dorsal est chargé de grenades buboniques remplies des pires souches pathogènes des usines à maladies. Chaque salve de ces ignobles engins répand l'épidémie, et les pistolets injecteurs gratifient leurs cibles de doses d'ignominie concentrées.",
                'sellQuantity' => 0,
                'category_id' => 9,
            ],
            [
                'user_id' => NULL,
                'title' => 'Bloodmaster, Herald of Khorne',
                'metaTitle' => 'Bloodmaster, Herald of Khorne',
                'slug' => 'Bloodmaster-Herald-of-Khorne-2019',
                'summary' => "Ce kit est fourni en 14 composants plastique, plus un socle rond de 40mm. " ,
                'price'	=> 19,
                'discount' =>	0,	
                'quantity' => 50,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Les Bloodmasters sont incontournables pour toute armée de Khorne, que vous partiez à la conquête du 41e Millénaire ou des Royaumes Mortels. En plus d'être des combattants de premier ordre, ces champions du Dieu du Sang rendent vos Bloodletters encore plus meurtriers grâce à leurs aptitudes d'aura.",
                'sellQuantity' => 0,
                'category_id' => 9,
            ],
            [
                'user_id' => NULL,
                'title' => 'Feculent Gnarlmaw',
                'metaTitle' => 'Feculent Gnarlmaw',
                'slug' => 'Feculent-Gnarlmaw-2018',
                'summary' => "Ce kit plastique contient les composants nécessaires pour assembler un Feculent Gnarlmaw. " ,
                'price'	=> 28,
                'discount' =>	0,	
                'quantity' => 0,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Partout où les servants de Nurgle se regroupent en grand nombre et où la pourriture bénie s’installe, des Feculent Gnarlmaws poussent dans le sol flétri. Ces arbres abjects résonnent du triste carillon des cloches de l’entropie, crachent des nuages de spores démoniaques, et dispersent des germes visqueux pour tapisser la terre labourée par les asticots sous leurs frondaisons. ",
                'sellQuantity' => 0,
                'category_id' => 9,
            ],
            [
                'user_id' => NULL,
                'title' => 'Infernal Enrapturess',
                'metaTitle' => 'Infernal Enrapturess',
                'slug' => 'Infernal-Enrapturess-2019',
                'summary' => "Ce kit plastique d'Infernal Enrapturess est fourni en 24 composants, plus un socle ovale de 60mm. " ,
                'price'	=> 29,
                'discount' => 0,	
                'quantity' => 10,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Maestros de la discordance, les Infernal Enrapturess emplissent le champ de bataille de hurlements de douleur mêlés de cris de joie débridée. Ce sont les virtuoses du chœur infernal de Slaanesh, vers qui sont attirées les légions démoniaques du Prince Noir.",
                'sellQuantity' => 0,
                'category_id' => 9,
            ],
            [
                'user_id' => NULL,
                'title' => 'Métabrutus ',
                'metaTitle' => 'Métabrutus ',
                'slug' => 'Metabrutus',
                'summary' => "Ce kit permet de positionner à loisir le torse et les bras de votre Métabrutus. Vous pouvez également orienter à votre guise la tête que vous aurez choisie parmi les 6 incluses." ,
                'price'	=> 73,
                'discount' =>	0,	
                'quantity' => 50,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Dans chaque Métabrutus est enfermé un être vivant, un space marine du Chaos qui a basculé dans la folie. L'enfermement dans cette parodie blasphématoire de Dreadnought n'a rien d'un honneur : c'est un tourment sans espoir de rémission, aussi n'est-il pas étonnant que l'hôte d'un Métabrutus soit fréquemment psychotique au dernier degré.",
                'sellQuantity' => 0,
                'category_id' => 9,
            ],
            [
                'user_id' => NULL,
                'title' => 'Élus de Mortarion',
                'metaTitle' => 'Élus de Mortarion',
                'slug' => 'Death-Guard-Chosen-Of-Mortarion-2020',
                'summary' => "Ce kit plastique en 20 composants permet d'assembler un Essaimeur Répugnant, un Délabreur Délétère, et un Champion Space Marine de la Peste. Il est fourni avec 1 socle rond Citadel de 40mm et 2 socles ronds Citadel de 32mm. " ,
                'price'	=> 50,
                'discount' =>	0,	
                'quantity' => 11,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Les Essaimeurs Répugnants sont des canaux vivants pour les miasmes et maladies du Jardin de Nurgle, alors que les Délabreurs Délétères affaiblissent l'ennemi en faisant sonner leur glas. Le Champion de la Peste noie les hordes adverses dans l'immondice de son gerbe-peste et neutralise les véhicules ennemis à coups de lance-peste.",
                'sellQuantity' => 0,
                'category_id' => 9,
            ],
            [
                'user_id' => NULL,
                'title' => 'Pinceau STC S Base',
                'metaTitle' => 'Pinceau STC S Base',
                'slug' => 'Synthetic-Base-Brush-Small-2021',
                'summary' => "Il s'agit d'un pinceau Citadel STC, dont les poils sont faits des meilleures fibres 100% synthétiques. " ,
                'price'	=> 3,
                'discount' =>	0,	
                'quantity' => 45,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Suffisamment petit pour accéder aux recoins, le pinceau S Base est idéal pour appliquer la peinture Citadel Base dans les endroits entourés de parties dont vous avez déjà traité les couleurs. Comme il s'agit d'un pinceau fin, il convient très bien aussi pour les rehauts sur les arêtes de vos figurines, et pour faire des finitions telles que les petites inscriptions et autres lentilles de verre.",
                'sellQuantity' => 0,
                'category_id' => 11,
            ],
            [
                'user_id' => NULL,
                'title' => 'Pinceau STC M Dry',
                'metaTitle' => 'Pinceau STC M Dry',
                'slug' => 'Synthetic-Drybrush-Medium-2021',
                'summary' => "Il s'agit d'un pinceau Citadel STC, dont les poils sont faits des meilleures fibres 100% synthétiques. " ,
                'price'	=> 2,
                'discount' =>	0,	
                'quantity' => 45,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "La technique dite du brossage à sec est un formidable moyen de détailler les reliefs de votre figurine, et le meilleur résultat s'obtient avec un pinceau à poils bien droits et raides. C'est pourquoi nous avons conçu nos pinceaux M Dry pour avoir un profil plat et pile la surface adéquate pour convenir à des figurines de formes et tailles diverses.",
                'sellQuantity' => 0,
                'category_id' => 11,
            ],
            [
                'user_id' => NULL,
                'title' => 'Warhammer 40,000:Set Peinture + Outils',
                'metaTitle' => 'Warhammer 40,000:Set Peinture + Outils',
                'slug' => '40k-Paint-and-Tool-Set-DE-IT-2020',
                'summary' => "Cette boîte contient un pinceau pour débuter Citadel, une paire de pince à dégrapper Citadel et un ébarboir" ,
                'price'	=> 49,
                'discount' =>	0,	
                'quantity' => 45,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "L'assemblage et la peinture de figurines sont des facettes pratiques du hobby agréables et de plus en plus gratifiantes au fil du temps. Pour débuter, il faut quelques outils et un assortiment de peinture, c'est pourquoi cette boîte propose les bases de votre futur outillage à hobby.

                Débutez avec une paire de confortables pinces pour détacher vos figurines de leur grappe, un ébarboir pour les apprêter avant la peinture, et un pinceau de la bonne taille pour appliquer les premières couleurs.",
                'sellQuantity' => 0,
                'category_id' => 10,
            ],
            [
                'user_id' => NULL,
                'title' => "Space Marines: Set Intercessors d'Assaut + Peinture",
                'metaTitle' => "Space Marines: Set Intercessors d'Assaut + Peinture",
                'slug' => 'Space-Marines-Paint-Set-DE-FR-IT-2020',
                'summary' => "Les six pots de 12ml fournis comprennent les couleurs indispensables pour peindre vos Intercessors aux couleurs des Ultramarines, et un pot de peinture Technical pour texturer vos socles." ,
                'price'	=> 30,
                'discount' =>	0,	
                'quantity' => 75,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Fonçant dans la mêlée, crachant une mort ardente avec leurs pistolets bolters lourds et maniant de redoutables épées tronçonneuses, les Intercessors d'Assaut font merveille pour porter le fer chez l'ennemi.

                Cette boîte est le moyen tout trouvé de commencer votre collection de Space Marines Primaris. Vous y trouverez trois Intercessors d'Assaut en plastique aux poses variées, la peinture pour les préparer au combat et un pinceau pour débuter. Ces figurines sont emboîtables, et ne nécessitent que des pinces pour les dégrapper et assembler; pas de colle, pas de salissure.",
                'sellQuantity' => 0,
                'category_id' => 10,
            ],
            [
                'user_id' => NULL,
                'title' => 'Nécrons: Set Guerriers + Peinture',
                'metaTitle' => 'Nécrons: Set Guerriers + Peinture',
                'slug' => 'Necrons-Paint-Set-DE-FR-IT-2020',
                'summary' => "Les six pots de 12ml fournis comprennent les couleurs indispensables pour peindre vos Guerriers Nécrons aux couleurs de la Dynastie Szarekhan, et deux pots de peinture Technical pour texturer vos socles et obtenir un effet vert luminescent" ,
                'price'	=> 24,
                'discount' =>	0,	
                'quantity' => 50,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Avançant de leur pas lourd et implacable, les légions immortelles des Nécrons manient un armement horrible. Leurs armures brunies sont baignées de l'étrange lueur verte de l'énergie maléfique qui les anime.

                Cette boîte est le moyen tout trouvé de commencer votre collection de Nécrons. Vous y trouverez trois Guerriers Nécrons en plastique aux poses variées, la peinture pour les préparer au combat et un pinceau pour débuter. Ces figurines sont emboîtables, et ne nécessitent que des pinces pour les dégrapper et assembler; pas de colle, pas de salissure.",
                'sellQuantity' => 0,
                'category_id' => 10,
            ],
            [
                'user_id' => NULL,
                'title' => 'Poignée de Peintre Citadel Colour',
                'metaTitle' => 'Poignée de Peintre Citadel Colour',
                'slug' => 'Citadel-Colour-Painting-Handle-2020',
                'summary' => "
                Cette poignée de peintre peut accueillir des socles de 25mm, 28mm, 32mm et 40mm. " ,
                'price'	=> 12,
                'discount' =>	0,	
                'quantity' => 1,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Tout d'abord, il y eut l'humble Poignée de Peintre Citadel, un outil simple qui rencontra tout de suite un vif succès, car il permettait entre autres de peindre une figurine tout en mangeant un sandwich au jambon, et sans mettre les doigts sur la peinture. Puis sortirent de plus gros modèles, des bras leurs poussèrent pour faciliter le montage, et d'autres se parèrent de rouge pour distinguer les figurines particulières pendant les séances de peinture à la chaîne. Cette version revue de la Poignée de Peintre Citadel Colour représente la plus nette amélioration du principe depuis sa sortie. Citadel a conservé tout ce qui faisait l'attrait de l'originale, mais en adjoignant le fruit de l'expérience accumulée.",
                'sellQuantity' => 0,
                'category_id' => 12,
            ],
            [
                'user_id' => NULL,
                'title' => "Poignée d'Assemblage Citadel",
                'metaTitle' => "Poignée d'Assemblage Citadel",
                'slug' => 'Citadel-Assembly-Handle-2018',
                'summary' => "La poignée proprement dite est identique à notre Poignée de Peintre Citadel, et comporte un mécanisme à ressort qui peut recevoir des socles ronds de jusqu'à 40mm ou ovales de jusqu'à 60mm – une fois que la colle est sèche, il vous suffit de détacher les mors et de vous servir de la poignée pour tenir fermement la figurine à peindre! " ,
                'price'	=> 17,
                'discount' =>	0,	
                'quantity' => 0,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Outil parfait pour assembler nos figurines les plus complexes, la Poignée d'Assemblage Citadel est conçue pour maintenir fermement les composants en place le temps que la colle sèche. Il arrive qu'il faille maintenir en place un composant minuscule pendant plusieurs minutes le temps que la colle prenne – cet outil est muni de mors flexibles à ressort qu'on peut orienter dans quasiment toutes les positions grâce à leurs articulations à rotules, ce qui vous dispense de tenir la pièce et vous permet de continuer à dégrapper les composants suivants. Ces mors peuvent aussi servir à maintenir des composants isolés pour que vous puissiez les peindre à part!
                ",
                'sellQuantity' => 0,
                'category_id' => 12,
            ],
            [
                'user_id' => NULL,
                'title' => 'Tapis de peinture Citadel',
                'metaTitle' => 'Tapis de peinture Citadel',
                'slug' => 'Citadel-Painting-Mat-2017',
                'summary' => "Un tapis de peinture Citadel pour protéger votre table." ,
                'price'	=> 17,
                'discount' =>	0,	
                'quantity' => 0,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Conçu pour protéger votre table de cuisine (ou votre établi de hobby attitré selon votre degré d'implication) des éclaboussures de peinture qui arrivent tôt ou tard à tout le monde, le tapis de peinture Citadel est fait de silicone souple avec des rebords pour empêcher la peinture de couler – plus besoin de mettre la nappe en péril! ",
                'sellQuantity' => 0,
                'category_id' => 12,
            ],
            [
                'user_id' => NULL,
                'title' => 'Pot à Eau Citadel',
                'metaTitle' => 'Pot à Eau Citadel',
                'slug' => 'Citadel-Water-Pot-2018',
                'summary' => "Le pot à eau fait 100mm de diamètre à la base, et 90mm de haut." ,
                'price'	=> 8,
                'discount' =>	0,	
                'quantity' => 0,
                'shop' => 1,
                'created_at' => date(now()),
                'updated_at' => date(now()),	
                'published_at' => date(now()),	
                'starts_at' => NULL,
                'ends_at' => NULL,
                'content' => "Mieux qu'un simple récipient, le Pot à Eau Citadel a été conçu par les peintres, pour les peintres. Moulé dans un plastique gris solide, il comporte sur sa face intérieure et son fond des fentes dont la texture optimise le nettoyage des pinceaux. Au bord, un canal permet de déposer les pinceaux à l'horizontale quand ils ne servent pas, et il y a contre le bord interne des fentes de largeur décroissante – une fois que vous avez rincé votre pinceau dans l'eau, faites-le glisser le long d'une fente pour bien lisser sa pointe!",
                'sellQuantity' => 0,
                'category_id' => 12,
            ],
        ]);
    }
}
