<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products_images')->insert([
            [
            'product_id' => 1,
            'first_img' => "Beasts_of_Chaos_01.webp",
            'second_img' => "Beasts_of_Chaos_02.webp",
            'third_img' => NULL,
            'fourth_img' => NULL,
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 2,
            'first_img' => "Kavalos_Deathriders_01.webp",
            'second_img' => "Kavalos_Deathriders_02.webp",
            'third_img' => "Kavalos_Deathriders_03.webp",
            'fourth_img' => NULL,
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 3,
            'first_img' => "Lord-Celestant_on_Stardrake_01.webp",
            'second_img' => "Lord-Celestant_on_Stardrake_02.webp",
            'third_img' => "Lord-Celestant_on_Stardrake_03.webp",
            'fourth_img' => "Lord-Celestant_on_Stardrake_04.web",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 4,
            'first_img' => "Sylvaneth_Treelord_Ancient_01.webp",
            'second_img' => "Sylvaneth_Treelord_Ancient_02.webp",
            'third_img' => "Sylvaneth_Treelord_Ancient_03.webp",
            'fourth_img' => "Sylvaneth_Treelord_Ancient_04.webp",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 5,
            'first_img' => "Morathi_01.webp",
            'second_img' => "Morathi_02.webp",
            'third_img' => "Morathi_03.webp",
            'fourth_img' => "Morathi_04.webp",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 6,
            'first_img' => "Rotigus_Rainmaker_01.webp",
            'second_img' => "Rotigus_Rainmaker_02.webp",
            'third_img' => "Rotigus_Rainmaker_03.webp",
            'fourth_img' => "Rotigus_Rainmaker_04.webp",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 7,
            'first_img' => "Belakor_DarkMaster_Lead_01.webp",
            'second_img' => "Belakor_DarkMaster_Lead_02.webp",
            'third_img' => "Belakor_DarkMaster_Lead_03.webp",
            'fourth_img' => "Belakor_DarkMaster_Lead_04.webp",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 8,
            'first_img' => "Lord_of_Change_01.webp",
            'second_img' => "Lord_of_Change_02.webp",
            'third_img' => "Lord_of_Change_03.webp",
            'fourth_img' => "Lord_of_Change_04.web",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 9,
            'first_img' => "Bloab_Rotspawned_01.webp",
            'second_img' => "Bloab_Rotspawned_02.webp",
            'third_img' => "Bloab_Rotspawned_03.webp",
            'fourth_img' => "Bloab_Rotspawned_04.webp",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 10,
            'first_img' => "Harbinger_of_Decay_01.webp",
            'second_img' => "Harbinger_of_Decay_02.webp",
            'third_img' => "Harbinger_of_Decay_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 11,
            'first_img' => "Corpse_Cart_Balefire_01.webp",
            'second_img' => "Corpse_Cart_Balefire_02.webp",
            'third_img' => "Corpse_Cart_Balefire_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 12,
            'first_img' => "Wight_King_with_Baleful_Tomb_Blade_01.webp",
            'second_img' => "Wight_King_with_Baleful_Tomb_Blade_02.webp",
            'third_img' => "Wight_King_with_Baleful_Tomb_Blade_03.webp",
            'fourth_img' => "Wight_King_with_Baleful_Tomb_Blade_04.webp",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 13,
            'first_img' => "Reikenor_the_Grimhailer_01.webp",
            'second_img' => "Reikenor_the_Grimhailer_02.webp",
            'third_img' => "Reikenor_the_Grimhailer_03.webp",
            'fourth_img' => "Reikenor_the_Grimhailer_04.webp",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 14,
            'first_img' => "Nighthaunt_Cairn_Wraith_01.webp",
            'second_img' => "Nighthaunt_Cairn_Wraith_02.webp",
            'third_img' => "",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 15,
            'first_img' => "Kritza_Rat_Prince_01.webp",
            'second_img' => "Kritza_Rat_Prince_02.webp",
            'third_img' => "Kritza_Rat_Prince_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 16,
            'first_img' => "MortisEngine_01.webp",
            'second_img' => "MortisEngine_02.webp",
            'third_img' => "MortisEngine_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 17,
            'first_img' => "Heavy_Intercessors_01.webp",
            'second_img' => "Heavy_Intercessors_02.webp",
            'third_img' => "Heavy_Intercessors_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 18,
            'first_img' => "Primaris_Redemptor_Dreadnought_01.webp",
            'second_img' => "Primaris_Redemptor_Dreadnought_02.webp",
            'third_img' => "Primaris_Redemptor_Dreadnought_03.webp",
            'fourth_img' => "Primaris_Redemptor_Dreadnought_04.webp",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 19,
            'first_img' => "Primaris_Chaplain_01.webp",
            'second_img' => "Primaris_Chaplain_02.webp",
            'third_img' => "Primaris_Chaplain_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 20,
            'first_img' => "SoBExorcist_01.webp",
            'second_img' => "SoBExorcist_02.webp",
            'third_img' => "SoBExorcist_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 21,
            'first_img' => "Stormlord_01.webp",
            'second_img' => "Stormlord_02.webp",
            'third_img' => "Stormlord_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 22,
            'first_img' => "Knight_Valiant_01.webp",
            'second_img' => "Knight_Valiant_02.webp",
            'third_img' => "Knight_Valiant_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 23,
            'first_img' => "Chaos_Lord_Box_01.webp",
            'second_img' => "Chaos_Lord_Box_02.webp",
            'third_img' => "Chaos_Lord_Box_03.webp",
            'fourth_img' => "Chaos_Lord_Box_04.webp",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 24,
            'first_img' => "Icon_Bearer_01.webp",
            'second_img' => "Icon_Bearer_02.webp",
            'third_img' => "Icon_Bearer_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 25,
            'first_img' => "Biologus_Putrifier_01.webp",
            'second_img' => "Biologus_Putrifier_02.webp",
            'third_img' => "Biologus_Putrifier_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 26,
            'first_img' => "Blood_master_of_Khorne_01.webp",
            'second_img' => "Blood_master_of_Khorne_02.web",
            'third_img' => "Blood_master_of_Khorne_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 27,
            'first_img' => "Feculent_Gnarlmaw_01.webp",
            'second_img' => "Feculent_Gnarlmaw_02.webp",
            'third_img' => "Feculent_Gnarlmaw_03.webp",
            'fourth_img' => "Feculent_Gnarlmaw_04.webp",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 28,
            'first_img' => "Infernal_Enrapturess_01.webp",
            'second_img' => "Infernal_Enrapturess_02.webp",
            'third_img' => "Infernal_Enrapturess_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 29,
            'first_img' => "Metabrutus_Helbrute_01.webp",
            'second_img' => "Metabrutus_Helbrute_02.webp",
            'third_img' => "Metabrutus_Helbrute_03.webp",
            'fourth_img' => "Metabrutus_Helbrute_04.webp",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 30,
            'first_img' => "Chosen_of_Mortarion_Lead_01.webp",
            'second_img' => "Chosen_of_Mortarion_Lead_02.webp",
            'third_img' => "Chosen_of_Mortarion_Lead_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 31,
            'first_img' => "SyntheticBaseBrushSmallLead_01.webp",
            'second_img' => NULL,
            'third_img' => NULL,
            'fourth_img' => NULL,
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 32,
            'first_img' => "SyntheticDryBrushMediumLead_01.webp",
            'second_img' => "",
            'third_img' => "",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 33,
            'first_img' => "40k_Paints_Tools_01.webp",
            'second_img' => "40k_Paints_Tools_02.webp",
            'third_img' => "40k_Paints_Tools_03.webp",
            'fourth_img' => "40k_Paints_Tools_04.webp",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 34,
            'first_img' => "SM_Paint_Set_01.webp",
            'second_img' => "SM_Paint_Set_02.webp",
            'third_img' => "SM_Paint_Set_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 35,
            'first_img' => "NEC_Paint_Set_01.webp",
            'second_img' => "NEC_Paint_Set_02.webp",
            'third_img' => "NEC_Paint_Set_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 36,
            'first_img' => "Painting_Handle_01.webp",
            'second_img' => "Painting_Handle_02.webp",
            'third_img' => "Painting_Handle_03.webp",
            'fourth_img' => "Painting_Handle_04.webp",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 37,
            'first_img' => "Third_Arm_Painting_Handle_01.webp",
            'second_img' => "Third_Arm_Painting_Handle_02.webp",
            'third_img' => "Third_Arm_Painting_Handle_03.webp",
            'fourth_img' => "Third_Arm_Painting_Handle_04.webp",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 38,
            'first_img' => "Citadel_Painting_Mat_01.webp",
            'second_img' => "",
            'third_img' => "",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
            [
            'product_id' => 39,
            'first_img' => "Water_Pot_01.webp",
            'second_img' => "Water_Pot_02.webp",
            'third_img' => "Water_Pot_03.webp",
            'fourth_img' => "",
            'fifth_img' => NULL,
            'sixth_img' => NULL,
            ],
        ]);
    }
}
